### ISSUE TITLE
Big repo support

### ISSUE THREAD

**Issue by IonicaBizau** [dciccale/git-committers#1]
@dciccale Like I commented [here](https://github.com/alessioalex/git-authors/issues/1) already, this will fail on big repositories since it uses `exec`.

**Comment by dciccale** [comment]
this module could be used, what do you think? https://www.npmjs.com/package/git-spawned-stream

**Comment by IonicaBizau** [comment]
I ended by using [`gitloc-parser`](https://github.com/yorkie/node-gitlog-parser) by @yorkie.

Here is some relevant discussion: https://github.com/IonicaBizau/git-stats/pull/55 

Thanks! :four_leaf_clover:
